blueprint:
  name: Motion Light with Conditions
  description: Turn a light on based on detected motion, but not when the TV is already on
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: This sensor will be synchronized with the light.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    target_light:
      name: Lights
      description: The lights to keep in sync.
      selector:
        target:
          entity:
            domain: light
conditions:
  - condition: state
    entity_id: sensor.tv_media_playback_status
    state: "off"

trigger:
  - platform: state
    entity_id: !input motion_sensor

action:
  - service: >
      {% if trigger.to_state.state == "on" %}
        light.turn_on
      {% else %}
        light.turn_off
      {% endif %}
    target: !input target_light
